### ISSUE TITLE
Oak updated but not added to particle

### ISSUE THREAD

**Issue by dominicjordan** [digistump/OakCore#58]
Not sure if this is the right place for this, correct me if I'm wrong.

I have updated and added my oak to my particle account. When I power on my oak it is burst blinking 3 times (I guess this is the config mode). I can't connect to the oak wifi network anymore, it is not showing. Also when I use the Particle cli I get the response that no devices are connected to my account.

What to do?

**Comment by digistump** [comment]
The forums are the best place -  issues on github tend to be best for
confirmed bugs in the code, since most of the community hangs around the
forums instead and is often eager to help - confusing I know with so many
things in so many places.

This thread might be a good place to start:
http://digistump.com/board/index.php/topic,2103.0.html for the issue you
are seeing.
